---
linters:
  BangFormat:
    enabled: true
  BemDepth:
    enabled: false
  BorderZero:
    convention: zero
  ColorKeyword:
      enabled: true
  ColorVariable:
    enabled: false
  Comment:
    enabled: true
  DeclarationOrder:
    enabled: false
  DisableLinterReason:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    style: same_line
  EmptyLineBetweenBlocks:
    enabled: false
  EmptyRule:
    enabled: true
  ExtendDirective:
    enabled: false
  FinalNewline:
    enabled: true
  HexLength:
    style: short
  HexNotation:
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  ImportPath:
    leading_underscore: false
    filename_extension: false
  Indentation:
    allow_non_nested_indentation: false
    character: space
    width: 2
  LeadingZero:
    style: include_zero
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    max_depth: 5
    ignore_parent_selectors: false
  PlaceholderInExtend:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: true
  PropertyUnits:
    enabled: false
  QualifyingElement:
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false
  SelectorDepth:
    max_depth: 3
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    style: one_space
  SpaceBeforeBrace:
    allow_single_line_padding: false
    style: space;
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    style: single_quotes
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TrailingZero:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: false
  UrlFormat:
    enabled: false
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: false
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: true